server:
  port: 8888

fabric:
  channelName: mychannel
  chaincodeName: mychaincode
  organizations:
    org1:
      mspID: Org1MSP
      certPath: /network/crypto-config/peerOrganizations/org1.hyperealty.com/users/User1@org1.hyperealty.com/msp/signcerts
      keyPath: /network/crypto-config/peerOrganizations/org1.hyperealty.com/users/User1@org1.hyperealty.com/msp/keystore
      tlsCertPath: /network/crypto-config/peerOrganizations/org1.hyperealty.com/peers/peer0.org1.hyperealty.com/tls/ca.crt
      peerEndpoint: peer0.org1.hyperealty.com:7051
      gatewayPeer: peer0.org1.hyperealty.com
    org2:
      mspID: Org2MSP
      certPath: /network/crypto-config/peerOrganizations/org2.hyperealty.com/users/User1@org2.hyperealty.com/msp/signcerts
      keyPath: /network/crypto-config/peerOrganizations/org2.hyperealty.com/users/User1@org2.hyperealty.com/msp/keystore
      tlsCertPath: /network/crypto-config/peerOrganizations/org2.hyperealty.com/peers/peer0.org2.hyperealty.com/tls/ca.crt
      peerEndpoint: peer0.org2.hyperealty.com:7051
      gatewayPeer: peer0.org2.hyperealty.com
    org3:
      mspID: Org3MSP
      certPath: /network/crypto-config/peerOrganizations/org3.hyperealty.com/users/User1@org3.hyperealty.com/msp/signcerts
      keyPath: /network/crypto-config/peerOrganizations/org3.hyperealty.com/users/User1@org3.hyperealty.com/msp/keystore
      tlsCertPath: /network/crypto-config/peerOrganizations/org3.hyperealty.com/peers/peer0.org3.hyperealty.com/tls/ca.crt
      peerEndpoint: peer0.org3.hyperealty.com:7051
      gatewayPeer: peer0.org3.hyperealty.com
